name: AI Service CI

on:
  push:
    paths:
      - 'ai_service/**'
      - '.github/workflows/ai-service.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        cd ai_service
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd ai_service
        python -m pytest

    - name: Lint with flake8
      run: |
        cd ai_service
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics